# pull the base image
FROM node:lts-alpine

# set the working direction
WORKDIR /app

# install app dependencies
COPY package.json ./

COPY yarn.lock ./

RUN yarn install
RUN yarn add serve

# add app
COPY . ./

RUN yarn build

EXPOSE 3000

# start client
CMD ["serve", "-s", "build"]