version: "3.0"
services:
  resume:
    image: ghcr.io/jr33d/resume-jreed-me:latest
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      SENDGRID_API_KEY:
      CONTACT_EMAIL:
      APP_EMAIL:
    restart: unless-stopped