version: "3"
services:
    nginx:
        depends_on:
          - api
          - client
        restart: always
        build:
          dockerfile: Dockerfile
          context: ./nginx
        ports:
          - "3050:80"

    client:
        container_name: resume-jreed-me_client
        build:
            context: ./client
            dockerfile: Dockerfile
        #ports:
        #    - "3000:3000"
        volumes:
            - ./client:/app

    api:
        container_name: resume-jreed-me-api
        build:
            context: ./server
            dockerfile: Dockerfile
        #ports:
        #    - "3001:3001"
        volumes:
            - ./server:/app