# pull the base image
FROM node:lts-alpine

# set the working direction
WORKDIR /app

# install app dependencies
COPY package.json ./

COPY yarn.lock ./

RUN yarn install

# add app
COPY . ./server

RUN yarn build

EXPOSE 3001

# start app
CMD ["yarn", "start"]