name: Build & Release App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-client:
    uses: ./.github/workflows/client.yml
  build-server:
    uses: ./.github/workflows/server.yml

  dockerize:
    needs: [build-client, build-server]
    uses: ./.github/workflows/docker.yml
    # with:
    #   artifact-url: jobs.build.outputs.artifact-url