name: Build & Release App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  client:
    uses: ./.github/workflows/client.yml
  server:
    uses: ./.github/workflows/server.yml

  dockerize:
    needs: [client, server]
    uses: ./.github/workflows/docker.yml