name: Build & Release App

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-client:
    uses: ./.github/actions/client.yml@1
  build-server:
    uses: ./.github/actions/server.yml

  dockerize:
    needs: [build-client, build-server]
    uses: ./.github/actions/docker.yml
    # with:
    #   artifact-url: jobs.build.outputs.artifact-url