# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Client Build and Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & Release App"]
    types: [requested]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v3
    - name: Building React Client
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'yarn'
        cache-dependency-path: 'client/yarn.lock'
    - run: yarn install
    - run: yarn run build
    - run: yarn test
