name: Client Build and Test

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v3
    - name: Building React Client
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'yarn'
        cache-dependency-path: 'client/yarn.lock'
    - run: yarn install
    - run: yarn build
  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
    - uses: actions/checkout@v3
    - name: Testing React Client
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'yarn'
        cache-dependency-path: 'client/yarn.lock'
    - run: yarn install
    - run: yarn test
