name: Docker Compose Build

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build & Release App"]
    types: [requested]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: docker-compose build